### ISSUE TITLE
A couple of corrections to the example games

### ISSUE THREAD

**Issue by rooklift** [GutenbergSource/66632-Smith-The-game-of-go#1]
In the example games:

* Game 1 - the Gutenberg text (but not image) gives move 91 as Q3 -- this should be Q13.
* Game 3 - the Gutenberg text gives move 305 as T19 -- this should be T7.

**Comment by jhellingman** [comment]
Game 1 - Source scans agree, so fixed to Q13.

Game 2 - Unfortunately no illustration, Gutenberg text matches scan (305. T 19 Takes). So will need some secondary source or other reason to accept this correction.

**Comment by rooklift** [comment]
T19 is illegal.

The game is also available in the [GoGoD](https://gogodonline.co.uk/) archive as file 1907-00-00a.sgf (attached). The game is rotated 180 degrees in that source.

[1907-00-00a.zip](https://github.com/GutenbergSource/66632-Smith-The-game-of-go/files/7499523/1907-00-00a.zip)

**Comment by jhellingman** [comment]
Thanks, that settles it!

**Comment by jhellingman** [comment]
Fixed, and thanks for the report. Re-posting to Project Gutenberg will follow soon.
